### ISSUE TITLE
inconceivable

### ISSUE THREAD

**Issue by liukongjun** [FuGangqiang/myblog#3]
没有 想到 竟然 还有我 喜爱的 math ！

**Comment by FuGangqiang** [comment]
math 前端用的是 [`MathJax`](https://github.com/mathjax/MathJax)。

**Comment by liukongjun** [comment]
mathjax 麻烦不麻烦？
我们公司 WEB教育 产品，能用吗？

**Comment by FuGangqiang** [comment]
很好用的，只要加载 mathjax 库，然后在代码 html 里面嵌入 `TeX` 代码就可以了。

**Comment by liukongjun** [comment]
yeah!   great!
关键是 TeX 代码 好编辑吗？

**Comment by liukongjun** [comment]
国内 有 先导WEB教育公司在做吗？

**Comment by liukongjun** [comment]
还有 您的 博客有后台吗？  markdown 编辑好 博客 怎么 管理呢？

**Comment by FuGangqiang** [comment]
`TeX` 这个学习数学排版的都应该了解的，

我没有博客后台：
- 这只是一个纯静态网页，部署在 github  上的
-  博文由 `markdown` 编写
- 用 `python` 脚本自动生成静态网页
